
print(tonumber("0x01B"))
print(tonumber(".34"))
print(tonumber("2.5"))
print(tonumber("2E2"))
print(tonumber("2E+2"))
print(tonumber("2E-2"))
print(tonumber("2.3E1"))
print(tonumber("9E0"))
print(tonumber("9E"))
print(tonumber("9E-"))
print(tonumber("9."))
print(tonumber(".9"))
print(tonumber("."))
print(tonumber(".e1"))
print(tonumber("e1"))
